### ISSUE TITLE
Clean jester.json

### ISSUE THREAD

**Issue by kbd-overlord** [kbd-overlord/humor-ai#1]
Plug in cleaning code in the beautifulsoup extraction cell, after the for loop

TODO:

- replace double quotes inside the text to single quotes, get rid of new line characters, escape slashes, tabs etc.
- format jokes in the form of a dialogue

RESOURCES:

https://towardsdatascience.com/text-preprocessing-steps-and-universal-pipeline-94233cb6725a
https://spacy.io/usage

**Comment by AlwaysSorrow** [comment]
Done, please check
