### ISSUE TITLE
Clean stupidstuff.json

### ISSUE THREAD

**Issue by kbd-overlord** [kbd-overlord/humor-ai#2]
Use code from jester.json cleaning and parsing. Make a new section in the notebook for cleaning stupidstuff.json

TODO:

- get rid of jokes with empty body (no text, check for empty string)
- remove category from .json
- replace double quotes inside the text to single quotes, get rid of new line characters, escape slashes, tabs etc.
- format jokes in the form of a dialogue

RESOURCES:

https://towardsdatascience.com/text-preprocessing-steps-and-universal-pipeline-94233cb6725a
https://spacy.io/usage

**Comment by AlwaysSorrow** [comment]
Done. Please check.
